target_hz: 10
window_seconds: 60
stride_seconds: 10
label_event_gap_seconds: 10
flatline_std_min: 1.0e-6
drift_slope_max_uv_per_s: 10.0
snr_db_min: 3.0
sensor_min_val: -10000.0
sensor_max_val: 10000.0
clip_fraction_max: 0.05
max_rejection_rate_per_source: 0.30
min_samples_per_family: 100
min_samples_per_species: 50
random_seed: 42
source_scaling: {}
